### ISSUE TITLE
can we have CLI verify the input image file exists?

### ISSUE THREAD

**Issue by deeppppp** [private-dreamnet/dreamtime#24]
currently it will throw this error if the input file doesn't exists:

cli -i test.png -o out.png
GPU IDs: [0]
Executing phase: dress_to_correct
Traceback (most recent call last):
  File "main.py", line 101, in <module>
  File "main.py", line 74, in main
  File "run.py", line 167, in process
  File "opencv_transform/dress_to_correct.py", line 12, in create_correct
  File "opencv_transform/dress_to_correct.py", line 19, in correct_color
AttributeError: 'NoneType' object has no attribute 'shape'

and that is not very descriptive...

**Comment by wisp101** [comment]
Fixed in [DreamPower](https://github.com/private-dreamnet/dreampower).
