### ISSUE TITLE
Execute on ubuntu

### ISSUE THREAD

**Issue by helloooo1132** [private-dreamnet/dreamtime#3]
Hello I have ubuntu 16.04 LTS

I give permision of execution at cli file, then when execute trhows this messages:

```
GPU IDs: [0]
Executing phase: dress_to_correct
Traceback (most recent call last):
  File "main.py", line 101, in <module>
  File "main.py", line 74, in main
  File "run.py", line 167, in process
  File "opencv_transform/dress_to_correct.py", line 12, in create_correct
  File "opencv_transform/dress_to_correct.py", line 19, in correct_color
AttributeError: 'NoneType' object has no attribute 'shape'
[13483] Failed to execute script main
```
I made something wrong?

Thanks!

**Comment by caaruiz** [comment]
How are you running cli. Cli needs an input file.

**Comment by deep-man-yy** [comment]
The error message appears when the CLI could not read the photo you want to transform. Are you sure the `--input` argument has the right path to the photo?
