### ISSUE TITLE
NOt working with GPU anymore

### ISSUE THREAD

**Issue by stv176** [private-dreamnet/dreamtime#45]
I have a 965M TI and it was working good before the update now keeps saying fail

**Comment by kolessios** [comment]
Could you provide more information? At the time of failure you may get an alert with common problems and in the end a URL, that URL is for us.

**Comment by stv176** [comment]
The URL isn't working for me i'm not allowed to enter, anyways with CPU i dont have any problem with the software but when i'm using the GPU keeps saying Fail and in the console says this: 

[17984] Failed to execute script main
 Traceback (most recent call last):
 File "main.py", line 348, in <module>
 File "main.py", line 243, in main
 File "run.py", line 146, in process
 File "gan.py", line 85, in initialize
 File "gan.py", line 172, in __define_G
 File "site-packages\torch\nn\modules\module.py", line 265, in cuda
 File "site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "site-packages\torch\nn\modules\module.py", line 199, in _apply
 File "site-packages\torch\nn\modules\module.py", line 265, in <lambda>
 File "site-packages\torch\cuda\__init__.py", line 164, in _lazy_init
 File "site-packages\torch\cuda\__init__.py", line 60, in _load_cudart
 File "site-packages\torch\cuda\__init__.py", line 33, in find_cuda_windows_lib
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 19: invalid start byte

**Comment by kolessios** [comment]
This error always happens when DreamTime and/or DreamPower are in a folder with special characters (accents, spaces, etc.), I recommend moving DreamPower or reinstalling DreamTime in another location.

**Comment by stv176** [comment]
Now is working, thankyou
