### ISSUE TITLE
Transformation Failed - Driver is too old ( But it is not )

### ISSUE THREAD

**Issue by levantocode** [private-dreamnet/dreamtime#75]
**Describe the bug**
When I use CPU it works fine, but when I try using GPU it crashes at the Transformation after around 10s. ( I took a screenshot trying with 3 transformations at the same time but it occurs with 1 anyway )

I have already updated my drivers and restarted the pc.
It keep saying that my gpu drivers is to old.. but it is actually not.

**Screenshots**
![err](https://user-images.githubusercontent.com/19788704/63896071-6879d300-c9c7-11e9-96e4-a7d3be4d88c8.png)

**Enviroment (please complete the following information):**
 - Version 1.1.0
 - OS: Windows 10 Pro x64
 - GPU: NVIDIA GeForce GTX 550 Ti ( NVIDIA CUDA 9.1.84 driver )

**Additional context**
Console Log Error:
```
> [6808] Failed to execute script main
 Traceback (most recent call last):
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module>
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 146, in process
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 85, in initialize
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 172, in __define_G
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 199, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda>
 File "C:\Program Files\Python36\lib\site-packages\torch\cuda\__init__.py", line 162, in _lazy_init
 File "C:\Program Files\Python36\lib\site-packages\torch\cuda\__init__.py", line 91, in _check_driver
 AssertionError: 
 The NVIDIA driver on your system is too old (found version 9010).
 Please update your GPU driver by downloading and installing a new
 version from the URL: http://www.nvidia.com/Download/index.aspx
 Alternatively, go to: https://pytorch.org to install
 a PyTorch version that has been compiled with your version
 of the CUDA driver.
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> script main
 Traceback (most recent call last):
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module>
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 146, in process
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 85, in initialize
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 172, in __define_G
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 199, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda>
 File "C:\Program Files\Python36\lib\site-packages\torch\cuda\__init__.py", line 162, in _lazy_init
 File "C:\Program Files\Python36\lib\site-packages\torch\cuda\__init__.py", line 91, in _check_driver
 AssertionError: 
 The NVIDIA driver on your system is too old (found version 9010).
 Please update your GPU driver by downloading and installing a new
 version from the URL: http://www.nvidia.com/Download/index.aspx
 Alternatively, go to: https://pytorch.org to install
 a PyTorch version that has been compiled with your version
 of the CUDA driver.
> [5856] Failed to execute
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]

```

**Comment by kolessios** [comment]
As @wisp101 and the error message said, if your drivers are up to date this means that your GPU is not compatible with the software.
