### ISSUE TITLE
Fail to transform

### ISSUE THREAD

**Issue by Marridreg** [private-dreamnet/dreamtime#90]
Upon trying to transform a picture, I get a Fail at the end, and this error traceback.

> Done! We have taken 115.01 seconds
> Executing phase: nude_to_watermark
> Traceback (most recent call last):
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 346, in <module>
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 243, in main
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 146, in process
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 85, in initialize
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 172, in __define_G
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in cuda
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 193, in _apply
 [Previous line repeated 1 more time]
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 199, in _apply
 File "C:\Program Files\Python36\lib\site-packages\torch\nn\modules\module.py", line 265, in <lambda>
 RuntimeError: CUDA out of memory. Tried to allocate 36.00 MiB (GPU 0; 2.00 GiB total capacity; 636.02 MiB already allocated; 2.81 MiB free; 15.98 MiB cached)
> Failed to execute script main
> [81968]
> Executing phase: maskfin_to_nude
> Executing phase: maskdet_to_maskfin
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]
> Executing phase: maskref_to_maskdet
> Executing phase: mask_to_maskref
> Executing phase: correct_to_mask
> Executing phase: dress_to_correct
> GPU IDs: [0]

![image](https://user-images.githubusercontent.com/42444570/65358527-cfa23600-dbc7-11e9-8134-13040d80c4e8.png)

 - Version [e.g. 1.1.0]
 - OS: [e.g. Windows 10.0.17763 Build 17763]

**Comment by kolessios** [comment]
You should see an alert with the reason for the problem, in this case the memory of your GPU has run out (you only have 2 GB). I recommend closing any program that may be using your GPU memory, you can use the Task Manager to see what programs consume it.

**Comment by Marridreg** [comment]
That was very kind of you, thank you for the reply.  I’ll look at my error messages more closely from now on.

Sent from Mail for Windows 10
