### ISSUE TITLE
error

### ISSUE THREAD

**Issue by medalawi** [private-dreamnet/dreamtime#96]
> [8] Failed to execute script main
 Traceback (most recent call last):
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 20, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 5, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 4, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torchvision\__init__.py", line 1, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torchvision\models\__init__.py", line 1, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torchvision\models\alexnet.py", line 1, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torch\__init__.py", line 79, in <module>
 ImportError: DLL load failed: %1 is not a valid Win32 application.
> [5052] Failed to execute script main
 Traceback (most recent call last):
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\main.py", line 20, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\run.py", line 5, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\BuildAgent\work\19c514061bf819a4\src\cli\gan.py", line 4, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torchvision\__init__.py", line 1, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torchvision\models\__init__.py", line 1, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torchvision\models\alexnet.py", line 1, in <module>
 File "C:\Program Files\Python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
 File "C:\Program Files\Python36\lib\site-packages\torch\__init__.py", line 79, in <module>
 ImportError: DLL load failed: %1 is not a valid Win32 application.

===========================================

I already install python

**Comment by kolessios** [comment]
Please use the [following format](https://github.com/private-dreamnet/dreamtime/issues/new?assignees=&labels=bug&template=bug_report.md&title=) for this type of errors.
